site_name: "fluree-py"
site_description: "A Python client for Flur.ee's HTTP API"
site_url: "https://crcresearch.github.io/fluree-py"
repo_url: "https://github.com/crcresearch/fluree-py"
repo_name: "crcresearch/fluree-py"
site_dir: "site"
watch: [mkdocs.yml, README.md, src/fluree_py]

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

plugins:
- search
- callouts
- literate-nav:
    nav_file: SUMMARY.md
- autorefs
- section-index
- git-revision-date-localized:
    enabled: !ENV [DEPLOY, false]
    enable_creation_date: true
    type: timeago
- coverage:
    page_path: coverage  # default
    html_report_dir: htmlcov  # default
- api-autonav:
    modules: ['src/fluree_py']
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        inventories:
        - https://docs.python.org/3/objects.inv
        options:
          # General
          find_stubs_package: true
          show_bases: true
          show_source: false
          extensions:
          - griffe_generics
          - griffe_warnings_deprecated
          - griffe_modernized_annotations
          - griffe_pydantic:
              schema: true
          # Headings
          heading_level: 1
          show_root_heading: true
          show_root_full_path: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # Members
          summary: true
          # Docstrings
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          merge_init_into_class: true
          # Signatures
          line_length: 120
          separate_signature: true
          show_signature_annotations: true
          show_overloads: true
          signature_crossrefs: true
          unwrap_annotated: false
theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.instant.preview
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github 
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference
extra_css:
- css/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "¤"

nav:
  - Home: index.md
  - Coverage report: coverage.md

extra:
  social:
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/fluree-py/