[project]
name = "fluree-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "James Sweet", email = "jsweet@nd.edu" }
]
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.10.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "testcontainers[generic]>=4.9.2",
]
