from typing import Any, Protocol

from fluree_py.http.protocol.mixin import SupportsCommit, SupportsContext, SupportsRequestCreation


class QueryBuilder(SupportsContext, SupportsRequestCreation, SupportsCommit, Protocol):
    def with_where(self, conditions: dict[str, Any]) -> "QueryBuilder": ...
    def with_group_by(self, fields: list[str]) -> "QueryBuilder": ...
    def with_having(self, condition: dict[str, Any]) -> "QueryBuilder": ...
    def with_order_by(self, fields: list[str]) -> "QueryBuilder": ...
    def with_opts(self, opts: dict[str, Any]) -> "QueryBuilder": ...
    def select(self, fields: dict[str, Any] | list[str]) -> "QueryBuilder": ...
