from typing import Any, Protocol

from fluree_py.http.protocol.mixin.context import SupportsContext
from fluree_py.http.protocol.mixin.request import SupportsRequestCreation


class SupportsTransaction(Protocol):
    def transaction(self) -> "TransactionBuilder": ...


class TransactionBuilder(SupportsContext, SupportsRequestCreation, Protocol):
    def with_insert(self, data: dict[str, Any]) -> "TransactionBuilder": ...
    def with_delete(self, data: dict[str, Any]) -> "TransactionBuilder": ...
    def with_where(self, clause: dict[str, Any]) -> "TransactionBuilder": ...
    def commit(self) -> dict[str, Any]: ...
