from typing import Any, Protocol

from fluree_py.http.protocol.mixin import SupportsCommitable
from fluree_py.http.protocol.mixin.context import SupportsContext
from fluree_py.http.protocol.mixin.request import SupportsRequestCreation 


class TransactionBuilder(SupportsContext, Protocol):
    def with_insert(self, data: dict[str, Any]) -> "TransactionReadyToCommit": ...
    def with_delete(self, data: dict[str, Any]) -> "TransactionReadyToCommit": ...
    def with_where(self, clause: dict[str, Any]) -> "TransactionBuilder": ...


class TransactionReadyToCommit(
    SupportsContext, SupportsRequestCreation, SupportsCommitable, Protocol
):
    def with_insert(self, data: dict[str, Any]) -> "TransactionReadyToCommit": ...
    def with_delete(self, data: dict[str, Any]) -> "TransactionReadyToCommit": ...
    def with_where(self, clause: dict[str, Any]) -> "TransactionReadyToCommit": ...
