from typing import Any, Protocol

import httpx

from fluree_py.ledger.protocol.context import SupportsContext


class SupportsHistory(Protocol):
    def history(self) -> "HistoryBuilder": ...


class HistoryBuilder(SupportsContext, Protocol):
    def with_history(self, history: list[str | None]) -> "HistoryBuilder": ...
    def with_t(self, t: dict[str, Any]) -> "HistoryBuilder": ...
    def with_commit_details(self, commit_details: bool) -> "HistoryBuilder": ...
    def request(self) -> httpx.Request: ...
    def commit(self) -> dict[str, Any]: ...
