from typing import Protocol

from fluree_py.ledger.protocol.create import CreateBuilder
from fluree_py.ledger.protocol.history import HistoryBuilder
from fluree_py.ledger.protocol.query import QueryBuilder
from fluree_py.ledger.protocol.transaction import TransactionBuilder


class SupportsLedgerOperations(Protocol):
    def create(self) -> "CreateBuilder": ...
    def transaction(self) -> "TransactionBuilder": ...
    def query(self) -> "QueryBuilder": ...
    def history(self) -> "HistoryBuilder": ...
