from typing import Any, Protocol, Self

from fluree_py.ledger.protocol.base import BaseBuilder, BaseReadyToCommit


class QueryBuilder(BaseBuilder, BaseReadyToCommit, Protocol):
    """Protocol for query builders."""

    def with_where(self, conditions: dict[str, Any]) -> Self: ...
    def with_group_by(self, fields: list[str]) -> Self: ...
    def with_having(self, condition: dict[str, Any]) -> Self: ...
    def with_order_by(self, fields: list[str]) -> Self: ...
    def with_opts(self, opts: dict[str, Any]) -> Self: ...
    def with_select(self, fields: dict[str, Any] | list[str]) -> Self: ...
