from typing import Any, Protocol

import httpx
from fluree_py.ledger.protocol.context import SupportsContext


class SupportsTransaction(Protocol):
    def transaction(self) -> "TransactionBuilder": ...


class TransactionBuilder(SupportsContext, Protocol):
    def with_insert(self, data: dict[str, Any]) -> "TransactionBuilder": ...
    def with_delete(self, data: dict[str, Any]) -> "TransactionBuilder": ...
    def with_where(self, clause: dict[str, Any]) -> "TransactionBuilder": ...
    def request(self) -> httpx.Request: ...
    def commit(self) -> dict[str, Any]: ...
